# Generated by Django 4.2.3 on 2023-07-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
