# Generated by Django 4.2.3 on 2023-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_book_json_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
